title = "Andreas D Kellas"
theme = "not-much"
languageCode = "en-us"
baseurl = "https://www.wunused.com/"
staticDir = ['static']

[menu]
    [[menu.main]]
        name = "home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "about"
        url = "/about/"
        weight = 2

    [[menu.main]]
        name = "publications"
        url = "/publications/"
        weight = 3

    [[menu.main]]
        name = "blog"
        url = "/posts/"
        weight = 4

[params]

    theme = "light"
    palette = "catpuccin"
    #showThemeNotice = true
    showPostsSummary = true

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4
